image: golang:1.21.7

stages:
  - build
  - test

variables:
  GOPATH: /go
  GOROOT: /usr/local/go
  PATH: /go/bin:/usr/local/go/bin:$PATH

before_script:
  - go version
  - go env

build:
  stage: build
  script:
    - go test -v .\lab_test.go
#    - go mod download
#    - go build -v ./...

test:
  stage: test
  script:
    - go test -v .\lab_test.go